<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rfc"
    nsURI="http://sap.fusesource.org/rfc" nsPrefix="rfc">
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
        eType="#//Group" containment="true" eOpposite="#//Group/repository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        eOpposite="#//Repository/groups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" containment="true" eOpposite="#//Function/group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" eType="#//Group"
        eOpposite="#//Group/functions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Structure"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//Structure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eTypeParameters name="S">
      <eBounds eClassifier="#//Structure"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" upperBound="-1" containment="true">
      <eGenericType eTypeParameter="#//Table/S"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Structure"/>
</ecore:EPackage>
