apiVersion: v1beta1
kind: Config
id: conf
items:
  - apiVersion: v1beta1
    kind: Pod
    id: fluentd
    desiredState:
      manifest:
        version: v1beta2
        id: fluentd
        containers:
          - name: fluentd
            image: fabric8/fluentd-kubernetes:latest
            imagePullPolicy: PullIfNotPresent
            env:
              - name: ELASTICSEARCH_SERVICE_NAME
                value: ELASTICSEARCH
              - name: FLUENTD_FLUSH_INTERVAL
                value: 10s
            volumeMounts:
              - name: docker-sock
                mountPath: /var/run/docker.sock
                readOnly: true
              - name: docker-containers
                mountPath: /var/lib/docker/containers
                readOnly: true
            privileged: true
        volumes:
          - name: docker-sock
            source:
              hostDir:
                path: /var/run/docker.sock
          - name: docker-containers
            source:
              hostDir:
                path: /var/lib/docker/containers
    labels:
      app: fluentd
