apiVersion: v1beta1
kind: Config
id: grafana-config
items:
  - apiVersion: v1beta1
    kind: ReplicationController
    id: grafana-rc
    desiredState:
      replicas: 1
      replicaSelector:
        app: grafana-viewer
      podTemplate:
        desiredState:
          manifest:
            version: v1beta1
            name: grafana-container
            containers:
              - name: grafana-image
                image: jimmidyson/grafana:latest
                imagePullPolicy: PullIfNotPresent
                ports:
                  - name: grafana-port
                    containerPort: 3000
                env:
                  - name: INFLUXDB_URL
                    value: http://${INFLUXDB_SERVICE_SERVICE_HOST}:${INFLUXDB_SERVICE_SERVICE_PORT}
                  - name: INFLUXDB_NAME
                    value: k8s
                  - name: INFLUXDB_USER
                    value: root
                  - name: INFLUXDB_PASSWORD
                    value: root
        labels:
          app: grafana-viewer
  - apiVersion: v1beta1
    kind: Service
    id: grafana-service
    containerPort: grafana-port
    port: 80
    selector:
      app: grafana-viewer
