#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
# nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
set -x
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.5.x86_64
export PATH=$JAVA_HOME/bin:$PATH
export OPENSHIFT_SSH_PORT=18101
export OPENSHIFT_SSH_HOST=$OPENSHIT_INTERNAL_IP
cd $OPENSHIFT_RUNTIME_DIR/fabric
bin/start