== Camel Forge Addon
:idprefix: id_ 
The Camel Forge addon enables developers to setup/manage/interact with Camel project. For example add new components, endpoints, routes and languages. This addon provides standalone functionality, and it can be re-used in other addons.
        
=== Depends on

[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|no
|no

|parser-java
|no
|no

|parser-xml
|no
|no

|cdi
|no
|no

|maven
|no
|no

|rest-client
|no
|no

|templates
|no
|no
|===


== Setup
This Addon requires the following installation steps.

=== Add configuration to pom.xml 
To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
[source,xml]
----
<dependency>
   <groupId>io.fabric8.forge</groupId>
   <artifactId>camel</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----
== Features
Get Camel Project Info:: 
To get information about Camel component, dataformat and language on a specific project (if it uses Camel off course!), just type
+
[source,java]
----
camel-info
----

Add a specific Camel component in a project:: 
For example if you want to add the Hazelcast component in your Camel project, just type
+
[source,java]
----
camel-add-component --name hazelcast
----

List all the components used in a specific project:: 
If you want to have a list of the components of your projects, just type
+
[source,java]
----
camel-list-component
----
