#!/bin/sh
#
#  Copyright 2005-2014 Red Hat, Inc.
#
#  Red Hat licenses this file to you under the Apache License, version
#  2.0 (the "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
#  implied.  See the License for the specific language governing
#  permissions and limitations under the License.
#

DIRNAME=`dirname "$0"`

# lets check if we are not about to join a fabric
if [ "x$FABRIC8_ZOOKEEPER_URL" = "x" ]; then

  # unless we explicitly disable it, lets auto-start an ensemble
  if [ "x$FABRIC8_ENSEMBLE_AUTO_START" = "x" ]; then
    FABRIC8_ENSEMBLE_AUTO_START=true
    export FABRIC8_ENSEMBLE_AUTO_START
  fi

  # unless we explicitly disable it, lets auto-start the agent
  if [ "x$FABRIC8_AGENT_AUTO_START" = "x" ]; then
    FABRIC8_AGENT_AUTO_START=true
    export FABRIC8_AGENT_AUTO_START
  fi
fi

exec "${DIRNAME}/karaf" "$@"
