# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$provisionScript = <<SCRIPT

yum install -y docker-io

systemctl enable docker

groupadd docker
usermod -a -G docker vagrant

# update limits
echo >> /etc/security/limits.conf
echo *        hard    nproc           8192 >> /etc/security/limits.conf
echo *        soft    nproc           8192 >> /etc/security/limits.conf
echo *        hard    nofile           8192 >> /etc/security/limits.conf
echo *        soft    nofile           8192 >> /etc/security/limits.conf

sed -i "s/^OPTIONS=.\*/OPTIONS='--selinux-enabled -H unix:\\/\\/var\\/run\\/docker.sock -H tcp:\\/\\/0.0.0.0:2375 --insecure-registry=172.0.0.0\\/8'/" /etc/sysconfig/docker

systemctl restart docker

SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/fedora-20"

  config.vm.network "private_network", ip: "172.28.128.4"

  config.vm.hostname = "fabric8-master.vagant.local"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2

    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell", inline: $provisionScript

end
